# -*- coding: utf-8 -*-
"""ML publicidad

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ibB2zi4RqT24audY7PKJPTQzLicHGyXj
"""

import pandas as pd
import matplotlib.pyplot as plt

# @title Texto de título predeterminado
data = pd.read_csv('https://raw.githubusercontent.com/Adrian-Cancino/Machine-Learning-ScikitLearn/refs/heads/main/Conjuntos%20de%20datos/Advertising.csv')
data.head()

data = data.iloc[:, 1:]
data.head()

data.info()

data.describe()

data.columns

columnas = ['TV', 'Radio', 'Newspaper'] # Exclude 'Sales' as it's the target variable
for columna in columnas:
  plt.plot(data[columna], data['Sales'], 'ro') # Pass x and y data as separate arguments
  plt.title('Ventas respecto a la publicidad en %s' %columna)
  plt.show() # Correctly call the show method

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

x = data['TV'].values.reshape(-1,1)
y = data['Sales'].values

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

print(x_train.shape)
print(x_test.shape)
lin_reg = LinearRegression()
lin_reg.fit(x_train, y_train)

predict = lin_reg.predict(x_test)
print(f"Predicciones:\n{predict}\n Reales:\n{y_test}")

from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test, predict)
rmse = np.sqrt(mse)
print(f"RMSE: {rmse}")

#R2
print('R2:' ,r2_score(y_test, predict))

plt.plot(x_test, y_test, 'ro')
plt.plot(x_test, predict, 'bo')
plt.show

def modelo_regresion_lineal(independiente):
  x = data[independiente].values.reshape(-1,1)
  y = data['Sales'].values
  x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
  lin_reg = LinearRegression()
  lin_reg.fit(x_train, y_train)
  predict = lin_reg.predict(x_test)
  print(f"Predicciones:\n{predict}\n Reales:\n{y_test}")
  from sklearn.metrics import mean_squared_error
  import numpy as np
  mse = mean_squared_error(y_test, predict)
  rmse = np.sqrt(mse)
  print(f"RMSE: {rmse}")
  print('R2:' ,r2_score(y_test, predict))
  plt.plot(x_test, y_test, 'ro')
  plt.plot(x_test, predict, 'bo')
  plt.show()

modelo_regresion_lineal('Radio')

modelo_regresion_lineal('Newspaper')

import seaborn as sns

x = data.drop(['Radio', 'Sales'], axis=1).values
  y = data['Sales'].values
  x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
  lin_reg = LinearRegression()
  lin_reg.fit(x_train, y_train)
  predict = lin_reg.predict(x_test)
  print(f"Predicciones:\n{predict}\n Reales:\n{y_test}")
  from sklearn.metrics import mean_squared_error
  import numpy as np
  mse = mean_squared_error(y_test, predict)
  rmse = np.sqrt(mse)
  print(f"RMSE: {rmse}")
  print('R2:' ,r2_score(y_test, predict))
  sns.regplot(x=y_test, y=predict)

x = data.drop(['Newspaper', 'Sales'], axis=1).values
  y = data['Sales'].values
  x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
  lin_reg = LinearRegression()
  lin_reg.fit(x_train, y_train)
  predict = lin_reg.predict(x_test)
  print(f"Predicciones:\n{predict}\n Reales:\n{y_test}")
  from sklearn.metrics import mean_squared_error
  import numpy as np
  mse = mean_squared_error(y_test, predict)
  rmse = np.sqrt(mse)
  print(f"RMSE: {rmse}")
  print('R2:' ,r2_score(y_test, predict))
  sns.regplot(x=y_test, y=predict)

#regresion polinomica
import pandas as pd
import numpy as np
years = [x for x in range(1,11)]
position = ["Puesto 1", "Puesto 2", "Puesto 3", "Puesto 4", "Puesto 5","Puesto 6", "Puesto 7", "Puesto 8", "Puesto 9", "Puesto 10"]
salary = [1000.0, 1150.0, 1260.0, 1600.0, 1900.0,2400.0, 3000.0, 4000.0, 5200.0, 6000.0]
data = {
    "posición": position,
    "años": years,
    "salario": salary
}

data = pd.DataFrame(data)
data.head()

plt.scatter(data["posición"], data["salario"])
    plt.title("Salario por Puesto")
    plt.xlabel("Puesto")
    plt.ylabel("Salario")
    plt.show()

x = data.iloc[:,1].values.reshape(-1, 1)
y = data.iloc[:,-1].values
regresion_multiple = LinearRegression()
regresion_multiple.fit(x, y)
plt.scatter(data['años'], data['salario'], color='blue')
plt.plot(x, regresion_multiple.predict(x), color='black')
plt.show()

import sklearn.preprocessing as pre
import sklearn.linear_model as lm
poly = pre.PolynomialFeatures(degree=9)
x_poly = poly.fit_transform(x)
regresion_2 = lm.LinearRegression()
regresion_2.fit(x_poly, y)
plt.scatter(data['años'], data['salario'])
plt.plot(data['años'], regresion_2.predict(poly.fit_transform(x)), color='red')
plt.title("Regresión Polinómica")
plt.xlabel("Años")
plt.ylabel("Salario")
plt.show()